ability to make celestial object without world
Slimefun-Addon-Community/Galactifun pull request #12
Opened 2021-01-31 19:19 UTC by Mooy1

2021-01-31 20:12 UTC, Seggan requested changes

2021-01-31 20:12 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/explorer/GalacticHolder.java
> + *
*holds

2021-01-31 20:12 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/Saturn.java
> + */
*example

2021-01-31 20:17 UTC, GallowsDove requested changes

2021-01-31 20:17 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/GalacticCategory.java
> +        super(PluginUtils.getKey("galactic_category"), null);
Should be Nonnull (based on annotation)

2021-01-31 20:17 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/GalacticListener.java
> +        CelestialWorld object = GalacticRegistry.getCelestialObject(e);
CelestialWorld that you get by getCelestialObject is really confusing, should be changed

2021-01-31 20:17 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/GalacticListener.java
> +        CelestialWorld object = GalacticRegistry.getCelestialObject(e);
Same as above

2021-01-31 20:17 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/GalacticListener.java
> +        CelestialWorld object = GalacticRegistry.getCelestialObject(e);
Same as above

2021-01-31 20:17 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/GalacticRegistry.java
> +    public static CelestialWorld getCelestialObject(@Nonnull String worldName) {
Should be getCelestialWorld

2021-01-31 20:17 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/Earth.java
> +import org.apache.commons.lang.Validate;
Unused import

2021-01-31 20:27 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/Galaxy.java
> +        return null;
placeholder til i make it

2021-01-31 20:27 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/GalacticCategory.java
> +        super(PluginUtils.getKey("galactic_category"), null);
placeholder til i make

2021-02-01 18:36 UTC, Seggan approved these changes

2021-02-01 19:01 UTC, GallowsDove approved these changes

2021-02-01 19:10 UTC, merged