Asteroid gen fix
Slimefun-Addon-Community/Galactifun pull request #136
Opened 2022-10-07 17:32 UTC by GallowsDove

## Changes

Fix spheres not generating in space-orbit

## Related Issues

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2022-10-07 22:27 UTC, ProfElements approved these changes
Looks good :0

2022-10-08 01:41 UTC, Seggan requested changes

2022-10-08 01:49 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/SimpleAlienWorld.java
> +    protected record CraterSettings(int octaves, double scale, double frequency, double amplitude, double noiseDepth) {
My bad, I think I've accidentally pressed something in intellij

2022-10-08 02:44 UTC, ProfElements approved these changes
LGTM

2022-10-08 22:20 UTC, Seggan approved these changes

2022-10-08 22:20 UTC, merged