Change Ticking System
Slimefun-Addon-Community/Galactifun pull request #138
Opened 2022-12-27 13:33 UTC by JustAHuman-xD

## Changes
Instead of iterating through all of the entities on the Server with a heavy method such as world#getLivingEntities().
It will now cache the entities UUID when it spawns it in. Then in the Ticking method we retrieve all of the entities with Bukkit#getEntity(UUID). 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2022-12-27 14:06 UTC, GallowsDove commented
Don't currently have the time to test unfortunately, but I'm not really confident that this will work in between server restarts. Please test it thoroughly.

2022-12-27 15:50 UTC, Seggan requested changes
Agree with @GallowsDove, you will still need to loop all entities at least still on server restart

2022-12-27 17:52 UTC, JustAHuman-xD commented
Oh yeah sorry, forgot that you dont remove the entities when they are too far away/on server stop, will do rq.

2022-12-28 15:08 UTC, GallowsDove commented
I think there might still be an issue with this. world.getLivingEntities() goes only through currently loaded entities, so any unloaded aliens that exist will not get looped, so will not get ticked later.

2022-12-28 16:38 UTC, JustAHuman-xD commented
I could listen to the chunk load event, not sure how heavy that would be though.

2022-12-28 16:40 UTC, GallowsDove commented
Yeah either that, or periodically update cache e.g. every 2 seconds. Would need performance testing to figure out

2022-12-28 18:31 UTC, Seggan commented
> I could listen to the chunk load event, not sure how heavy that would be though.

Isn't where a `Chunk#getLivingEntities`?

2022-12-28 22:02 UTC, JustAHuman-xD commented
> Isn't there a `Chunk#getLivingEntities`?

Its Chunk#getEntities, but yeah the thought was I would listen for that event and get the entities, but I wasn't sure how heavy listening to the chunk load event. Maybe I also cache the chunk coords that way I dont bother running that again after the chunk has been loaded for the first time.

2022-12-28 22:23 UTC, Seggan commented
Nah, caching would cause some stuff with respawning stuff. In any case, its still lighter than using `World#getLivingEntities` on every 2 ticks

2022-12-29 01:38 UTC, JustAHuman-xD commented
Caching coordinates & uuids, shouldnt affect anything with respawning

2023-01-04 15:07 UTC, JustAHuman-xD commented
> I think there might still be an issue with this. world.getLivingEntities() goes only through currently loaded entities, so any unloaded aliens that exist will not get looped, so will not get ticked later.

Also I believe using world#getEntities() upon say startup it does actually return all of the entities of the world but unsure atm. I used it with a separate project and it worked regardless of the chunks being loaded but I need to look into it further.

2023-01-11 22:51 UTC, JustAHuman-xD commented
This theoretically works, not sure the performance difference but I can test it soon™️

2023-01-12 18:26 UTC, Seggan requested changes

2023-01-12 18:26 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/managers/AlienManager.java
> +                }
```suggestion
                if (alienSet.contains(uuid)) continue;
```

2023-01-12 19:47 UTC, Seggan approved these changes

2023-01-12 19:47 UTC, Seggan commented
Will merge once you confirm that it works

2023-01-12 20:53 UTC, JustAHuman-xD commented
👍 alright, did a little bit of testing prior and had no issues but definitely need to do more. I will also get 2 spark reports to compare the new system and the old.

2023-01-12 21:02 UTC, JustAHuman-xD commented
I'll also check if the whole chunk system is necessary. I don't think it will be because of the 

mob.setRemoveWhenFarAway(true);

But I'll definitely check. (I didn't earlier because didn't have time to do much more than write the system.)

2023-02-22 13:08 UTC, JustAHuman-xD commented
Sorry that this PR completely died, I'll take a look at the remaining issues tonight and hopefully wrap it up

2023-02-26 18:18 UTC, JustAHuman-xD commented
Okay yeah I have confirmed that the mobs *are* persistent after a restart time to do some other checks

2023-02-26 18:20 UTC, JustAHuman-xD commented
though it might be because they were in spawn chunks in any case Im doing a lot of testing rn

2023-04-01 14:17 UTC, JustAHuman-xD commented
Going to close this so that I can do this from not the main branch of my fork, and so I can do the changes that have been discussed in addon-devs in discord

2023-04-01 14:17 UTC, closed without merging