sphere, refactor, improve
Slimefun-Addon-Community/Galactifun pull request #20
Opened 2021-02-06 20:22 UTC by Mooy1

## Changes

## Related Issues

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-02-06 20:27 UTC, ProfElements commented
You did confirm that world generation still works right? with all currently available planets?

2021-02-06 20:28 UTC, Mooy1 commented
ye, just need to test after i merged with master

2021-02-06 20:28 UTC, ProfElements commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/UniversalObject.java
> +            orbiter.orbiting = this;
This is a little confusing to read imo, but looks good otherwise.

2021-02-07 22:34 UTC, GallowsDove requested changes

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
>      }
This would probably have to be implemented through a ticker and would have to use the world#setTime.

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/AbstractTerrain.java
> +    private final String name;
use several lines for this

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
> -    }
This changes the behavior to be hostile by default, instead of until attacked.

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/UniversalCategories.java
> +}
I have no idea what this class is for, add a javadoc please

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/StarSystem.java
> +import org.bukkit.Material;
Unused imports

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/commands/GenSphereCommand.java
> +import io.github.mooy1.infinitylib.PluginUtils;
Unused import

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +    }
This does nothing, unless delayed

2021-02-07 22:34 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/util/Sphere.java
> +     */
Probably shouldn't be a part of javadoc, just a regular comment

2021-02-07 22:54 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
> -    }
If you have a more effective way of achieving the desired behavior you are free to PR it, but please don't change it

2021-02-08 01:54 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/Galaxy.java
> +    }
because later we may add stats to all galaxies like type or smth

2021-02-08 01:54 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
> -    }
you want passive creepers?

2021-02-08 01:55 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/UniversalCategories.java
> +}
its categories for items, will add javadoc tho

2021-02-08 01:56 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/util/Sphere.java
> +     */
looks messier outside the javadoc imo

2021-02-08 01:56 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/util/Sphere.java
> +     */
ill just delete instead lul

2021-02-08 01:59 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +    }
why?

2021-02-08 07:48 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
> -    }
That was the plan, having agressive charged creepers all over planet sounds terrifying

2021-02-08 07:49 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +    }
Because the player isn't alive yet, so you can't apply effects to him

2021-02-08 13:29 UTC, Seggan submitted a review, later dismissed

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Atmosphere.java
> +    private final World.Environment environment;
I suggest using an `@Builder` to clean up this mess

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/GalaxyType.java
*Elliptical

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Gravity.java
>              new PotionEffect(PotionEffectType.JUMP, Integer.MAX_VALUE, this.jump, false, false).apply(p);
:NotLikeThis: `p.applyEffect(new PotionEffect)`

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Orbit.java
> +    private final long time;
that makes no sense

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/CelestialWorld.java
> +    private static final int MAX_ALIENS = ConfigUtils.getInt("aliens.max-per-player", 1, 16, 8);
this wouldnt allow for some aliens to be rarer than others

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/Terrain.java
> +
maybe a config option for flat bedrock?

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/BaseRegistry.java
>      public static final CelestialWorld MARS = new Mars();
maybe `EARTH_ORBIT` before `THE_MOON`?

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
i still like alien creeper better @GallowsDove opinion?

2021-02-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/util/Sphere.java
> +
why is it package private?

2021-02-08 13:29 UTC, Seggan commented on src/main/resources/config.yml
> +#
why 1-16? cant we have higher amounts?

2021-02-08 13:30 UTC, Seggan commented
Oops i pressed the wrong button. consider those as requested changes

2021-02-08 13:37 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/Terrain.java
> +
I mean, this is a default implementation, if you want flat bedrock then you can just override it.

2021-02-08 13:38 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
No strong opinion, not like it really matters to me what it's called.

2021-02-08 14:11 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/alien/Alien.java
> +        LivingEntity entity = (LivingEntity) world.spawnEntity(loc, this.type);
So that no messy reuireNonNull on loc. GetWorld

2021-02-08 14:11 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Atmosphere.java
> +    private final World.Environment environment;
Ill rewrite the effects system

2021-02-08 14:12 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/CelestialWorld.java
> +    private static final int MAX_ALIENS = ConfigUtils.getInt("aliens.max-per-player", 1, 16, 8);
There chances make them rarer

2021-02-08 14:13 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/util/Sphere.java
> +
Those are local vars

2021-02-08 14:14 UTC, Mooy1 commented on src/main/resources/config.yml
> +#
Mm i guess we could

2021-02-08 14:19 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Atmosphere.java
> +    private final World.Environment environment;
i mean *all* of the fields, not just the effects

2021-02-08 14:20 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
well you are the author of it...

2021-02-08 14:20 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/util/Sphere.java
> +
why didnt i notice that

2021-02-08 18:00 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/Terrain.java
> +
ill do flat by default and if they want spiky it can be added in the generateBlock method of planet

2021-02-08 18:02 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/MutantCreeper.java
imo naming an alien 'alien' doesnt really make sense

2021-02-08 18:06 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/AtmosphereBuilder.java
> +
you realize theres a lombok [annonation](https://projectlombok.org/features/Builder) for this?

2021-02-08 18:07 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +    }
they are alive because its called after they click respawn

2021-02-08 18:07 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +    }
tho it prob shud just be tested

2021-02-08 19:12 UTC, Seggan requested changes

2021-02-08 19:12 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/EffectType.java
> +    public static final EffectType WITHER = new EffectType("Radioactive", PotionEffectType.WITHER);
enum please

2021-02-08 19:17 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +    }
ah u right lul

2021-02-08 19:17 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/EffectType.java
> +    public static final EffectType WITHER = new EffectType("Radioactive", PotionEffectType.WITHER);
not enum cuz people should be able to make there own

2021-02-08 19:37 UTC, Seggan approved these changes

2021-02-09 00:06 UTC, GallowsDove approved these changes

2021-02-09 04:30 UTC, Mooy1 commented
Tested all world gens, working fine 👍

2021-02-09 04:30 UTC, merged