Simplified constructors, added register method, moved tasks
Slimefun-Addon-Community/Galactifun pull request #26
Opened 2021-02-17 03:09 UTC by Mooy1

## Changes
title

## Related Issues
x

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-02-17 12:52 UTC, Seggan requested changes

2021-02-17 12:52 UTC, Seggan commented on README.md
> +Inspiration taken from ClayTech and GalactiCraft.
Perhaps "the mod GalactiCraft"? some people might not know that galacticraft is a mod

2021-02-17 12:52 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/Galactifun.java
>                  "",
https://discord.gg/SqD3gg5SAU

2021-02-17 13:33 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
>      }
how is "of" even a method name

2021-02-17 13:33 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/CelestialWorld.java
Why is there an empty line? (kinda nitpicking)

2021-02-17 16:05 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
>      }
its used a lot in the jdk. i.e `EnumSet.of`

2021-02-17 17:20 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
>      }
https://docs.oracle.com/javase/tutorial/datetime/overview/naming.html

2021-02-17 20:11 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
>      }
i just didnt want daysHours(int days, int hours)

2021-02-17 20:12 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
>      }
maybe the other 2 could be 'ofDays' and 'ofHours'

2021-02-17 20:59 UTC, Seggan approved these changes

2021-02-17 21:10 UTC, Seggan approved these changes

2021-02-18 23:36 UTC, Seggan commented
Eh, too lazy to re-review and re-approve. Consider approved from me

2021-02-23 14:27 UTC, Seggan requested changes

2021-02-23 14:27 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/Leech.java
> +        if (eaten == null) {
`@Nullable` or `@Nonnull`, depending on which one is in the interface

2021-02-23 14:27 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/earth/Earth.java
>          } else {
semicolon not comma

2021-02-24 20:44 UTC, Mooy1 commented
I still gotta test most of the recent commits btw

2021-02-25 13:25 UTC, Seggan reviewed
Note I'm not requesting changes, just commenting.

2021-02-25 13:25 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/Atmosphere.java
> +    @Getter
:NotLikeThis: the entire *reason* i did bigdecimal was to have accuracy when filling in the "other gases". if we have a validation error dont blame me

2021-02-25 13:25 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/AtmosphereBuilder.java
>      public AtmosphereBuilder setEnd() {
I have tried to do that when working with sfwarfare, but the bossbar remains and theres a bedrock pillar that wed need to remove

2021-02-25 13:25 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/AtmosphereBuilder.java
> +
u can use `this.composition.values().stream().mapToDouble(Double::doubleValue).sum()` to replace all this

2021-03-03 06:09 UTC, Mooy1 commented
did some testing and it all seems to be working as far as i can tell

2021-03-04 01:29 UTC, Seggan commented
Can you *pleeeeeease* merge this now

2021-03-04 18:09 UTC, ProfElements commented
KLGTM

2021-03-05 02:29 UTC, merged