Start alien spawn
Slimefun-Addon-Community/Galactifun pull request #27
Opened 2021-02-18 23:39 UTC by Seggan

## Changes
I added 2 new mobs to Titan: the leech and the skywhale. Skywhales are giant passive phantoms that don't burn, leeches have a chance to steal an item from your inventory when attacking. Also changed up Titan generation a little, and changed ice types of Europa and Enceladus. Mobs: moved spawning to a ticker and expanded the API.

## Related Issues
N/A

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-02-18 23:50 UTC, ProfElements commented
👍 LGTM

2021-02-19 01:32 UTC, Mooy1 approved these changes

2021-02-19 01:32 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/Leech.java
> +        e.getDrops().clear();
store eaten items in persistent data so they aren't lost across restarts

2021-02-19 01:32 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +            CelestialWorld world = CelestialWorld.getByWorld(e.getEntity().getWorld());
why change to celestial world

2021-02-19 01:32 UTC, Mooy1 requested changes
accidently approved in the other one

2021-02-19 13:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/listener/CelestialListener.java
> +            CelestialWorld world = CelestialWorld.getByWorld(e.getEntity().getWorld());
oops

2021-02-22 16:30 UTC, merged