Remove persistent alien and added prefix to world names
Slimefun-Addon-Community/Galactifun pull request #30
Opened 2021-03-08 06:18 UTC by Mooy1

i havent tested world stuff yet but my persistant itemstack array works

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-03-08 17:19 UTC, Seggan requested changes
I really think we should keep persistentalien. also wont approve until tested

2021-03-08 17:19 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
> +        int extra = (days - 1) * 24000 + hours * 1000;
we can slow down as well by redoing the same tick twice. it already works like that

2021-03-08 18:36 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
> +        int extra = (days - 1) * 24000 + hours * 1000;
im just worried because the javadoc mentions it could mess up scheduled tasks

2021-03-08 21:02 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/DayCycle.java
> +        int extra = (days - 1) * 24000 + hours * 1000;
it only says that for `setAbsoluteTime` and `setFullTime`, not `setTime`

2021-03-09 13:50 UTC, Seggan reviewed
Tested?

2021-03-09 16:10 UTC, Mooy1 commented
just need to test time stuff

2021-03-15 12:20 UTC, Seggan commented
Btw when u need a review pls request one from me i usually just look at my notifications

2021-03-22 13:14 UTC, Seggan requested changes

2021-03-22 13:14 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/Alien.java
if you make it protected then at least rename it to `maxHealth`

2021-03-22 13:14 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/AlienWorld.java
> -
we need the blockstorage...

2021-03-22 15:34 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/world/AlienWorld.java
> -
fixed by my slimefun pr

2021-03-22 20:03 UTC, Seggan requested changes

2021-03-22 20:03 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/BaseItems.java
> +    }
as i said we already have a cheat category

2021-03-23 00:43 UTC, Mooy1 commented
tested all my recent changes, seems to be working

2021-03-23 14:16 UTC, Seggan requested changes
ah, how i love that "suggest changes" feature

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/items/AssemblyTable.java
> +    });
why not just have a class with all the recipe types in it...

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/items/LaunchPadCore.java
> +            ItemStack slotItem = menu.getItemInSlot(FUEL_SLOT);
looking though i see a lot of `TODO improve`. just how would we improve this and those other instances?

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/Venus.java
> +        populators.add(new LakePopulator(80, Material.LAVA));
why 80?

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/aliens/Leech.java
> + *
```suggestion
/**
 * Class for the leech, an alien of Titan. They can steal your items when attacking
 *
```

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/aliens/Leech.java
> +        }
that gives a very small chance of eating an item. we need it to select from the *actual* items in the inventory

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/aliens/Leech.java
> +                attacker.getHealth() + 2)
```suggestion
        attacker.setHealth(Math.min(
                this.maxHealth,
                attacker.getHealth() + 2)
```
since you made the health var `protected`, might as well do this

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/earth/EarthOrbit.java
now that i think about it, we dont even *need* surface area now that we dont have a world border

2021-03-23 14:16 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/categories/AssemblyCategory.java
> +
tested

2021-03-23 19:03 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/CelestialBody.java
> -     */
looked nicer since none of the other fields had them, and the method to get it had the units

2021-03-23 19:04 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/AssemblyTable.java
> +    });
so that there isnt a bunch of public maps

2021-03-23 19:05 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/LaunchPadCore.java
> +            ItemStack slotItem = menu.getItemInSlot(FUEL_SLOT);
just there to remind me or anyone to rewrite it later

2021-03-23 19:06 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/earth/EarthOrbit.java
true, maybe just an enum of Sizes for the display item?

2021-03-23 19:11 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/LaunchPadCore.java
> +            ItemStack slotItem = menu.getItemInSlot(FUEL_SLOT);
for that one specifically, we should use a map of some sort instead of iterating and comparing every fuel

2021-03-23 19:19 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/earth/EarthOrbit.java
just remove it completely. we dont really need to show the surface ara

2021-03-23 19:20 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/items/AssemblyTable.java
> +    });
public maps?

2021-03-23 19:23 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/Leech.java
> +            }
36?

2021-03-23 21:38 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/AssemblyTable.java
> +    });
the RECIPES and ITEMS maps would need to be public in order for the RecipeTypes class to access it

2021-03-23 21:40 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/aliens/Leech.java
> +            }
27 inv + 9 in hotbar, but i need to add armor slots and stuff anyway

2021-03-24 12:52 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/items/AssemblyTable.java
> +    });
ok then

2021-03-24 12:52 UTC, Seggan approved these changes

2021-03-24 17:56 UTC, merged