Updated InfinityLib, Improvements to structure format
Slimefun-Addon-Community/Galactifun pull request #35
Opened 2021-03-26 20:03 UTC by Mooy1

## Changes
updated InfinityLib methods, working on improving structure format

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-04-06 19:51 UTC, Mooy1 commented
not quite done but ready for review

2021-04-07 01:03 UTC, Seggan requested changes

2021-04-08 13:29 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/structures/blocks/StructureBlock.java
> +    }
donnt you think "cache" is better than cached? just my opinion

2021-04-13 19:21 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/Galactifun.java
> +        }
dont you have to save the config?

2021-04-13 20:25 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/Galactifun.java
> +        }
o ya

2021-04-14 19:27 UTC, Seggan approved these changes

2021-04-14 20:13 UTC, merged