Stargates
Slimefun-Addon-Community/Galactifun pull request #41
Opened 2021-06-04 01:50 UTC by Seggan

## Changes

Added stargates

## Related Issues

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-06-04 02:01 UTC, Mooy1 requested changes
I think the ComponentPosition stuff could be cleaned up a bit too but if its works its fine

2021-06-04 16:52 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/goals/FleeGoal.java
> +        Galactifun.inst().registerListener(new Listener() {
i cant put the listener in the alien class bc the way goals work. i *can* put em in a static tho

2021-06-04 16:53 UTC, Seggan commented
Still have some stuff left to work on but I'll be offline for the next 2 days

2021-06-08 19:04 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/goals/FleeGoal.java
> +        Galactifun.inst().registerListener(new Listener() {
i couldnt find a way. also it *shouldn't* be part of alien class because the goals are detached from aliens

2021-06-08 19:05 UTC, Seggan commented
Stargates are now indestructible when activated, and they will no longer teleport when the destination Stargate is not activated

2021-06-09 03:13 UTC, Mooy1 approved these changes

2021-06-09 03:13 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/StargateController.java
> +                throw new IllegalStateException("Portal doesn't have state: " + portal.getLocation());
Maybe set it to the correct material instead?

2021-06-09 16:07 UTC, merged