Improved Register System + cleanup
Slimefun-Addon-Community/Galactifun pull request #44
Opened 2021-06-17 18:15 UTC by Mooy1

## Changes
- Added back launch messages
- Changed CelestialWorld to PlanetaryObject
- Changed register methods for Alien and PlanetaryObject
- Changed how Aliens are added to AlienWorlds
- Cleaned up Utils
- Updated InfinityLib
- Added StructureManager
- Moved some stuff to constructor in Alien and most UniversalObjects
- Improved BossBarStyle
- Moved WorldSetting stuff to methods in WorldManager and AlienWork
- Changed Orbit to use radians
- Updated listeners to private and added priorities
- Changed fuel system to stored fuel type rather than efficiency cuz mixing fuels is probably bad
- Removed ItemChoice

## Related Issues
x

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-06-18 20:44 UTC, Seggan requested changes
Lotsa typos

2021-06-18 20:44 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/WorldManager.java
> +        galactifun.runAsync(() -> {
bukkit methods arent thread safe

2021-06-18 20:44 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/WorldManager.java
> +    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
you know highest = first executed, right?

2021-06-18 20:44 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/universe/saturn/Titan.java
> +                int height = (int) (55 + 30 * + (startHeight * startHeight));
erm `30 * +`????

2021-06-18 20:44 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/CoreCategory.java
> +            new CustomItem(Material.END_STONE, "&bThe Universe"), new GalacticExplorer()); // TODO explorer could be used in rockey
rocket

2021-06-18 20:44 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/core/commands/SphereCommand.java
> +        p.sendMessage(ChatColor.GREEN + "Generated!");
timings still might help

2021-06-18 20:44 UTC, Seggan commented on src/main/resources/config.yml
> +  # Messages while rocket it launching
is

2021-06-18 20:55 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/types/PlanetaryType.java
> +public final class PlanetaryType extends UniversalType {
ye i figured some people may want to make their own

2021-06-18 20:56 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/universe/saturn/Titan.java
> +                int height = (int) (55 + 30 * + (startHeight * startHeight));
dunno, thats how it was before lol

2021-06-18 20:59 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/WorldManager.java
> +    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
it goes low -> high then monitor

2021-06-20 00:16 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/aliens/Alien.java
> +            if (rand.nextInt(100) > this.spawnChance) {
no random.nextDouble(bound)

2021-06-20 18:06 UTC, Seggan commented
Gonna review when I have time

2021-06-20 18:26 UTC, Seggan approved these changes

2021-06-21 22:28 UTC, Mooy1 commented
Should probably be merged before any other request because i can't cleanup any conflicts for 2 weeks

2021-06-21 23:42 UTC, Seggan commented
I'm always leave the owner to merge

2021-06-21 23:42 UTC, merged