Protection
Slimefun-Addon-Community/Galactifun pull request #45
Opened 2021-07-12 15:09 UTC by Seggan

## Changes

Added the protection system

## Related Issues

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-07-12 16:37 UTC, Mooy1 requested changes

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/aliens/Alien.java
> +    }
there can never be 2 aliens registered to same id so equals should probably be left as defaut ==

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/UniversalObject.java
> +        }
shouldnt this be part of all space objects?

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/UniversalObject.java
> +        return this.id.equals(other.id);
same as alien, no object can have the same id

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Orbit.java
>      public static final Orbit NONE = new Orbit(0, 0);
cant remember what i added it for, just delete lol

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/AtmosphericEffect.java
> +    }
same as alien, cant have same id as other

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/ProtectionManager.java
> +public final class ProtectionManager {
this should be a singleton because of static collection

2021-07-12 16:37 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +    public static final Set<Material> IMPERMEABLE_BLOCKS = EnumSet.noneOf(Material.class);
static collection

2021-07-12 18:21 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/UniversalObject.java
> +        }
no this basically keeps star systems from orbiting galaxies bc system orbits would take literal months

2021-07-12 19:07 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +    public static final Set<Material> IMPERMEABLE_BLOCKS = EnumSet.noneOf(Material.class);
whats wrong with that

2021-07-13 05:53 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +    public static final Set<Material> IMPERMEABLE_BLOCKS = EnumSet.noneOf(Material.class);
causes memory leaks cause of bukkit

2021-07-13 05:54 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/UniversalObject.java
> +        }
ya thats how it should be, youll need a ton of fuel

2021-07-13 05:57 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +    public static final Set<Material> IMPERMEABLE_BLOCKS = EnumSet.noneOf(Material.class);
it could go in the protection manager if thats what its used for

2021-07-13 05:58 UTC, Mooy1 approved these changes
just those, we could discuss the solar system thing later but imo it should be more realistic.

2021-07-13 18:32 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/util/Util.java
> +    public static final Set<Material> IMPERMEABLE_BLOCKS = EnumSet.noneOf(Material.class);
thats an enum set. enums dont cause memory leaks

2021-07-13 18:33 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/UniversalObject.java
> +        }
ok then

2021-07-13 19:44 UTC, merged