Lots of small changes
Slimefun-Addon-Community/Galactifun pull request #50
Opened 2021-08-06 00:03 UTC by Seggan

## Changes

Lots of small things:
- Titan Frozen Carbon Forests now generate dry ice instead of ice
- Changed Stargate address generation algorithm
- Added Space Heaters
- Added Ion Whatevericalledthems
- Added Sulfur block
- Added Ventstone
- Added chunk versions. These are used to mark new world gen so we can tell that "Mooyite is found in Mars chunk version 3 or higher"
- Fixed Rocket launch bugs
- Fixed `WorldManager#getWorld`

I also added Landing Beacons. These have 3 modes: Allow All, Player Only, and Disabled. If it's set to Allow All, all rockets landing in the same chunk will be redirected to the Landing Beacon. This is useful as the Rocket impl uses `World#getHighestBlockAt` which can result in you landing on top of your base instead of inside. Player Only will only redirect rockets flown by the same player that placed the Landing Beacon. Useful for keeping intruders out there with the Martians while you relax in luxury in your base. Disabled will, well, not redirect *any* rockets.

I won't be available for the next 3 days but I'll be back Monday.

## Related Issues

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-08-06 00:47 UTC, Mooy1 requested changes

2021-08-06 00:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/atmosphere/AtmosphereBuilder.java
> +    public AtmosphereBuilder addGas(@Nonnull Gas gas, double percentage) {
why rename? imo it reads weird to have addGas(Gas.)

2021-08-06 00:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/SimpleAlienWorld.java
> +        }
would be cleaner to just do this in constructor rather than lazy load

2021-08-06 00:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/LandingBeacon.java
> +    public enum Mode {
since its public id move it to its own class called LandingMode or smth

2021-08-06 00:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/base/universe/saturn/Titan.java
> +        if (this.generator == null) {
same here, initialize in constructor

2021-08-06 00:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/AlienWorld.java
> +    protected abstract int getChunkVersion();
What is the chunk version for? and if we were to use it, we should find a way to do it that doesnt require the dev to update it manually

2021-08-06 01:19 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/AlienWorld.java
> +    protected abstract int getChunkVersion();
> Added chunk versions. These are used to mark new world gen so we can tell that "Mooyite is found in Mars > > chunk version 3 or higher"

2021-08-06 02:18 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/AlienWorld.java
> +    protected abstract int getChunkVersion();
ah, this time i didn't read the description lol

2021-08-06 02:21 UTC, Mooy1 commented
Also, i don't really like the idea of landing beacons since it doesn't really make sense to land a rocket through a roof. I think they should have to unlock stargates to get this ability

2021-08-09 15:41 UTC, Seggan commented
> a hole

Then you can't seal the area

2021-08-09 15:44 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/SimpleAlienWorld.java
> +        }
yes but the world is loaded on register, not in the constructor

2021-08-09 22:41 UTC, Seggan commented
Did a cleanup of `Rocket#launch`, you can now also land properly into the void

2021-08-09 22:45 UTC, Mooy1 approved these changes
just that

2021-08-09 22:45 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/worlds/AlienWorld.java
> +                        list.add(new BlockPopulator() {
add this after calling getPopulators so people cant remove it

2021-08-10 02:26 UTC, Mooy1 approved these changes
lgtm

2021-08-10 13:26 UTC, merged