RELEASE (yay)
Slimefun-Addon-Community/Galactifun pull request #53
Opened 2021-09-08 17:51 UTC by Seggan

## Changes

Made it ready for release.
- Updated to RC-28
- Added recipes
- Added Automatic Door
- Increased protecting block range. As I tested gameplay, I realized 100 block range only takes care of the smallest rooms
- Added more sealable blocks
- Added Super Fan to increase range further
- Added Laserite
- Added Fusion Reactor
- A lot of bug fixes

## Related Issues

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-09-08 23:47 UTC, Mooy1 requested changes

2021-09-08 23:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/items/spacesuit/SpaceSuit.java
> +    private static final NamespacedKey SPACE_SUIT_KEY = AbstractAddon.createKey("space_suit");
ur meant to do Galactifun.createKey()

2021-09-08 23:47 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/util/BlockPositionSet.java
> +public final class BlockPositionSet implements Set<BlockPosition> {
You can do some unsafe casting instead to bypass that. iirc just do (Class) Set.class

2021-09-09 17:20 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/util/BlockPositionSet.java
> +public final class BlockPositionSet implements Set<BlockPosition> {
See Discord

2021-09-09 22:52 UTC, Mooy1 approved these changes
woop

2021-09-09 22:55 UTC, merged