improvements
Slimefun-Addon-Community/Galactifun pull request #7
Opened 2021-01-30 20:20 UTC by Mooy1

2021-01-30 20:53 UTC, GallowsDove commented
Wouldn't it be good to move the static declarations like MOON_LIKE into another class outside the API?

2021-01-30 21:01 UTC, ProfElements requested changes
Overall I think its pretty good, though having default material intertwined with the api should not be done.

Why was `TeleportCommand` renamed to `GalacticTeleport` ?

2021-01-30 21:02 UTC, GallowsDove reviewed
Also as stated, default types should stay away from the API.

2021-01-30 22:39 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
the point of them is so that people can use them for there own planet but have similar properties to the base ones. thats why they have "_LIKE"

2021-01-30 22:40 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Gravity.java
> +    public static final Gravity MARS_LIKE = new Gravity(.378);
same as above

2021-01-30 22:43 UTC, Mooy1 commented
renamed teleport cuz GalacticTeleport is more descriptive.

2021-01-30 22:45 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
I have to agree with ProfElements, I don't think they belong there. Devs can still use reference from a separate class that just contains these.

2021-01-30 22:57 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
why shouldnt they be there then

2021-01-30 23:06 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
Because they provide absolutely no utility, other than being used for a specific planet and for "reference", which could be said about just anything

2021-01-30 23:24 UTC, ProfElements commented
GalacticTeleport doesnt denote it is a command, though I do think having a the prefix does give it more descriptiveness

2021-01-30 23:26 UTC, ProfElements commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
I personally think these type of values should have a seperate utility class rather then being in the api, they provide no use if people dont use them in the api so having a seperate utility class people include instead of cluttering the api is the priority.

2021-01-30 23:55 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/CelestialObject.java
> +    @Nonnull private final DayCycle solarType;
This still isn't resolved

2021-01-31 00:07 UTC, GallowsDove commented
I don't see a reason to request review when you haven't addressed the issues above.

2021-01-31 00:38 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
There utility is that people can use them to create planets with similar properties without having to come up with the 5+ params on there own. It also gives reference to what those params might mean. And having a seperate class for these is more cluttered then placing them in their own class lul

2021-01-31 00:39 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/CelestialObject.java
> +    @Nonnull private final DayCycle solarType;
outdated

2021-01-31 00:40 UTC, Mooy1 commented
> GalacticTeleport doesnt denote it is a command, though I do think having a the prefix does give it more descriptivenes

tru

2021-01-31 00:46 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
and "no use if people dont use them in the api" can be said for any part of the api. And i do think they would be used more often than not whether its direct usage or just reference.

2021-01-31 00:50 UTC, GallowsDove requested changes
Just these details and should be fine

2021-01-31 00:50 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/Moon.java
> +        super(name, distance, surfaceArea, gravity, solarType, atmosphere, terrain);
Again should be dayCycle

2021-01-31 00:50 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/Planet.java
> +        super(name, distance, surfaceArea, gravity, solarType, atmosphere, terrain);
same here

2021-01-31 00:51 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
Let's let Seggan decide, no point in arguing.

2021-01-31 00:53 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
I think a compromise id do is only adding ones that i can see multiple other uses for. So I changed the moon atmosphere one to just "EMPTY" as it could be used for asteroids, moons, etc.

2021-01-31 00:54 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Gravity.java
> +    public static final Gravity MARS_LIKE = new Gravity(.378);
removed mars one. might change moon ones name to fit the api tho

2021-01-31 00:57 UTC, GallowsDove commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
I mean, it's not like we would be removing them. Just create a GravityType class and paste all the gravities there.

2021-01-31 01:26 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
I have to agree with mooy. We are only adding some presets that everyone knows how they're like. If they don't need it, just let em make their own! Note that I'm not promoting integration of solar system into api. I agree with dove and elements in that we should preferably keep them as separated as possible.

2021-01-31 01:28 UTC, Seggan commented
> 
> 
> GalacticTeleport doesnt denote it is a command, though I do think having a the prefix does give it more descriptiveness

I agree. Maybe something like `GFTPCommand`?

2021-01-31 01:31 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/Terrain.java
> +    public void generateChunkData(@Nonnull World world, @Nonnull Random random, int chunkX, int chunkZ,
Wow ure getting good at this

2021-01-31 01:35 UTC, Seggan requested changes

2021-01-31 01:35 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/milkyway/solarsystem/Mars.java
> +                Terrain.HILLY_CAVES);
Theyre not really proper caves, theyre cavers

2021-01-31 01:35 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/CelestialObject.java
> +    protected abstract Material generateBlock(@Nonnull Random random, int top, int x, int y, int z);
Javadocs? I dont get what certain methods are for

2021-01-31 01:40 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/attributes/Atmosphere.java
> +    public static final Atmosphere MOON_LIKE = new Atmosphere(
> I mean, it's not like we would be removing them. Just create a GravityType class and paste all the gravities there.

This is exactly what is there but messier...

2021-01-31 01:41 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/CelestialObject.java
> +    protected abstract Material generateBlock(@Nonnull Random random, int top, int x, int y, int z);
will do

2021-01-31 01:46 UTC, Mooy1 commented
> > GalacticTeleport doesnt denote it is a command, though I do think having a the prefix does give it more descriptiveness
> 
> I agree. Maybe something like `GFTPCommand`?

Maybe *GalactiportCommand*

2021-01-31 02:12 UTC, Seggan commented
Sure

2021-01-31 02:24 UTC, Seggan requested changes

2021-01-31 02:24 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/terrain/Cave.java
> +        this.ratio = ratio * 2;
why `ratio * 2`

2021-01-31 02:25 UTC, Mooy1 commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/terrain/Cave.java
> +        this.ratio = ratio * 2;
because the noise generates from -1 to 1, then i add 1 to that so its 0 - 2.

2021-01-31 02:30 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/api/universe/attributes/terrain/Cave.java
> +        this.ratio = ratio * 2;
thats a multiply 2. why u do that

2021-01-31 02:49 UTC, Seggan approved these changes

2021-01-31 02:49 UTC, merged