Fix potential problems (StarGate)
Slimefun-Addon-Community/Galactifun pull request #96
Opened 2021-11-13 13:27 UTC by zimzaza4

## Changes

If the player's destination is not an alien world, don't give the player Metadata

## Related Issues

hmm
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break world generation, mob spawning, and the like.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

2021-11-13 17:38 UTC, Seggan requested changes

2021-11-13 17:38 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/items/StargateController.java
> +            if (world != null) e.getPlayer().setMetadata("CanTpAlienWorld", new FixedMetadataValue(Galactifun.instance(), true));
Add braces please

2021-11-30 13:31 UTC, zimzaza4 commented on src/main/java/io/github/addoncommunity/galactifun/base/items/StargateController.java
> +            if (world != null) e.getPlayer().setMetadata("CanTpAlienWorld", new FixedMetadataValue(Galactifun.instance(), true));
ok

2021-11-30 15:04 UTC, Seggan requested changes

2021-11-30 15:04 UTC, Seggan commented on src/main/java/io/github/addoncommunity/galactifun/base/items/StargateController.java
> +            // Check if the destination is an alien world
this comment is kinda misleading. maybe "check if the player is teleporting to an alien world, and if so, allow them to"?

2021-12-03 20:58 UTC, Seggan approved these changes

2021-12-05 03:45 UTC, ProfElements approved these changes
LGTM

2021-12-05 20:49 UTC, merged